"""
report.py — Week 9 interim report visuals and Slide 3 summary generator.

Ported from parent report.py.
Orchestrates eda.py, reads quality_metrics.json and split_manifest.json,
renders slide3_summary.md and README_eda.md.
All comments and docstrings are in English.
File I/O uses utf-8-sig encoding.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths — sourced from config for pipeline consistency
# ---------------------------------------------------------------------------

from src.config import (  # noqa: E402
    PROJECT_ROOT,
    VISUALS_DIR,
    QUALITY_METRICS_PATH,
    SPLIT_MANIFEST_PATH,
    EDA_TABLES_PATH,
    SLIDE3_PATH,
    README_EDA_PATH,
    CLEAN_DATASET_PATH,
)

BASE_DIR = PROJECT_ROOT  # preserve original name

# Expected PNG outputs — keep in sync with eda.py
_VISUAL_CAPTIONS: dict[str, str] = {
    "01_label_marginals.png": "Marginal frequency of each PTSD symptom label, sorted descending.",
    "02_label_cooccurrence.png": "Co-occurrence count matrix for all label pairs.",
    "02b_label_correlation.png": "Pearson correlation (phi coefficient) between binary label vectors.",
    "03_cardinality.png": "Distribution of label-set size per record (0 = hard-negative).",
    "04_length_by_platform.png": "Word and character count distributions per platform (violin).",
    "05_platform_x_type.png": "Stacked bar: record counts across platform × example_type.",
    "06_severity_x_label.png": "Heatmap of label frequency segmented by severity level.",
    "07_explicitness_x_label.png": "Heatmap of label frequency segmented by explicitness category.",
    "08_slang_top20.png": "Top-20 most frequent military slang tokens across the dataset.",
}


# ---------------------------------------------------------------------------
# Slide 3 template renderer
# ---------------------------------------------------------------------------

_SLIDE3_TEMPLATE = """\
### Dataset & EDA — Week 9 Interim

- **Source:** Synthetic Hebrew military-slang utterances generated by `prompt_factory1240`
  across 4 platforms: whatsapp, tweet, reddit, diary.
- **Size:** {N_raw} raw → {N_clean} after G-Eval LLM-as-a-Judge filter ({pct_kept:.1f}% kept).
- **Label space:** {n_labels} PTSD-symptom labels, multi-label
  (mean cardinality {mean_card:.2f}; includes hard-negative class with zero labels).
- **Class balance:** rarest = `{rarest_label}` ({rarest_n} examples),
  most frequent = `{top_label}` ({top_n} examples).
  JS-divergence train↔test = {js:.4f}.
- **Split:** Iterative Stratification (Sechidis et al., 2011) 75/25,
  seed={seed}. Every label present in both folds (all sanity gates passed).
  Train N={n_train} | Test N={n_test}.
- **Stratifier:** `{stratifier}` ({skmll_version}).
- **Known limitations:** Small N, fully synthetic origin, no human inter-annotator
  agreement measured yet (planned Week 10).
"""


def render_slide3(
    metrics_path: Path,
    manifest_path: Path,
    eda_tables_path: Path,
    output_path: Path,
) -> None:
    """
    Fill in the Slide 3 template from persisted JSON artifacts.
    Raises FileNotFoundError with a helpful message if any input is missing.
    """
    missing = [p for p in [metrics_path, manifest_path, eda_tables_path] if not p.exists()]
    if missing:
        names = ", ".join(p.name for p in missing)
        raise FileNotFoundError(
            f"Missing required input files: {names}\n"
            "Run quality_judge.py → eda.py → split.py first."
        )

    with open(metrics_path, encoding="utf-8-sig") as f:
        metrics: dict = json.load(f)

    with open(manifest_path, encoding="utf-8-sig") as f:
        manifest: dict = json.load(f)

    with open(eda_tables_path, encoding="utf-8-sig") as f:
        tables: dict = json.load(f)

    N_raw = metrics["total_generated"]
    N_clean = metrics["total_accepted"]
    pct_kept = (N_clean / max(N_raw, 1)) * 100

    label_marg: dict = tables.get("label_marginals", {})
    # Filter out synthetic __NEG__ label if present
    real_labels = {k: v for k, v in label_marg.items() if not k.startswith("__")}

    sorted_labels = sorted(real_labels.items(), key=lambda x: x[1])
    rarest_label, rarest_n = sorted_labels[0] if sorted_labels else ("N/A", 0)
    top_label, top_n = sorted_labels[-1] if sorted_labels else ("N/A", 0)

    slide = _SLIDE3_TEMPLATE.format(
        N_raw=N_raw,
        N_clean=N_clean,
        pct_kept=pct_kept,
        n_labels=len(real_labels),
        mean_card=tables.get("mean_label_cardinality", 0.0),
        rarest_label=rarest_label,
        rarest_n=rarest_n,
        top_label=top_label,
        top_n=top_n,
        js=manifest.get("js_divergence_train_test", 0.0),
        seed=manifest.get("seed", 1240),
        n_train=manifest.get("n_train", "?"),
        n_test=manifest.get("n_test", "?"),
        stratifier=manifest.get("stratifier", "iterative_train_test_split"),
        skmll_version=manifest.get("skmultilearn_version", "?"),
    )

    with open(output_path, "w", encoding="utf-8-sig") as f:
        f.write(slide)

    logger.info("Slide 3 summary -> %s", output_path)


# ---------------------------------------------------------------------------
# README_eda.md generator
# ---------------------------------------------------------------------------


def render_readme(output_path: Path) -> None:
    """Generate README_eda.md cross-linking every chart PNG with one-sentence captions."""
    lines = [
        "# EDA Visuals — PTSD Hebrew Slang Dataset",
        "",
        "All charts generated by `eda.py`. Each PNG is 300 DPI, saved under `visuals/`.",
        "",
        "| Chart | Description |",
        "|-------|-------------|",
    ]
    for fname, caption in _VISUAL_CAPTIONS.items():
        lines.append(f"| ![{fname}](visuals/{fname}) | {caption} |")

    lines += [
        "",
        "## Generation pipeline",
        "",
        "```",
        "python quality_judge.py   # Pillar 1 — G-Eval filter → dataset1240.clean.json",
        "python eda.py             # Pillar 2 — EDA charts    → visuals/*.png",
        "python split.py           # Pillar 3 — Stratified split → train/test_dataset.json",
        "python report.py          # Pillar 4 — Summary docs  → slide3_summary.md",
        "```",
        "",
        "## Notes",
        "- Hard-negative records (`example_type=hard_negative`) have empty `labels=[]` and are included in all charts.",
        "- Hebrew tick labels rendered via `arabic_reshaper` + `python-bidi` for correct RTL display.",
    ]

    with open(output_path, "w", encoding="utf-8-sig") as f:
        f.write("\n".join(lines))

    logger.info("README_eda -> %s", output_path)


# ---------------------------------------------------------------------------
# Verify chart files exist
# ---------------------------------------------------------------------------


def verify_charts() -> list[str]:
    """Return list of expected chart filenames that are missing."""
    missing = []
    for fname in _VISUAL_CAPTIONS:
        p = VISUALS_DIR / fname
        if not p.exists():
            missing.append(fname)
        elif p.stat().st_size < 20_000:
            missing.append(f"{fname} (suspiciously small: {p.stat().st_size} bytes)")
    return missing


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def run_report_pipeline(
    metrics_path: str | Path = QUALITY_METRICS_PATH,
    manifest_path: str | Path = SPLIT_MANIFEST_PATH,
    eda_tables_path: str | Path = EDA_TABLES_PATH,
    slide3_path: str | Path = SLIDE3_PATH,
    readme_path: str | Path = README_EDA_PATH,
    run_eda: bool = True,
    eda_input: str | Path = CLEAN_DATASET_PATH,
) -> None:
    """
    Full report generation: optionally re-run EDA, then render docs.

    run_eda=True: triggers eda.py pipeline to regenerate charts before rendering.
    run_eda=False: assumes charts already exist (faster for re-runs).
    """
    if run_eda:
        logger.info("Running EDA pipeline …")
        from src.eda import run_eda_pipeline
        run_eda_pipeline(input_path=eda_input, tables_path=eda_tables_path)

    # Check charts
    missing = verify_charts()
    if missing:
        logger.warning("Missing or tiny chart files: %s", missing)
    else:
        logger.info("All %d chart files present and non-empty.", len(_VISUAL_CAPTIONS))

    logger.info("Rendering docs …")
    render_slide3(
        metrics_path=Path(metrics_path),
        manifest_path=Path(manifest_path),
        eda_tables_path=Path(eda_tables_path),
        output_path=Path(slide3_path),
    )
    render_readme(output_path=Path(readme_path))

    logger.info("Done.")
    logger.info("slide3_summary.md -> %s", slide3_path)
    logger.info("README_eda.md     -> %s", readme_path)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate Week 9 interim report artifacts")
    parser.add_argument("--metrics", default=str(QUALITY_METRICS_PATH))
    parser.add_argument("--manifest", default=str(SPLIT_MANIFEST_PATH))
    parser.add_argument("--tables", default=str(EDA_TABLES_PATH))
    parser.add_argument("--slide3", default=str(SLIDE3_PATH))
    parser.add_argument("--readme", default=str(README_EDA_PATH))
    parser.add_argument(
        "--no-eda",
        action="store_true",
        help="Skip EDA chart regeneration (use existing visuals/)",
    )
    parser.add_argument("--eda-input", default=str(CLEAN_DATASET_PATH))
    args = parser.parse_args()

    run_report_pipeline(
        metrics_path=args.metrics,
        manifest_path=args.manifest,
        eda_tables_path=args.tables,
        slide3_path=args.slide3,
        readme_path=args.readme,
        run_eda=not args.no_eda,
        eda_input=args.eda_input,
    )
